apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: nexus.vodafone.com:443/nodejs
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regsecret


